<?php

/* You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

 

Constraints:

    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.

 */

function findTheDifference($s, $t) {
    $len = strlen($s);
    for ($i = 0; $i < $len; $i++) {
        $t[strpos($t, $s[$i])] = '1';
    }   
    return str_replace('1', '', $t);

    // $len = strlen($t);
    // for ($i = 0; $i < $len; $i++) {
    //     $countS = substr_count($s, $t[$i]);
    //     $countT = substr_count($t, $t[$i]);
    //     if ($countS !== $countT) return $t[$i];
    // }
}

var_dump(findTheDifference("a", "aa"));